# Generated by Django 3.1.3 on 2020-11-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='data_utworzenia',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='telefon',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
