# Generated by Django 3.1.3 on 2020-11-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0002_auto_20201128_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=80, null=True)),
                ('cena', models.FloatField(null=True)),
                ('kategoria', models.CharField(choices=[('Domowe', 'Domowe'), ('Zewnętrzne', 'Zewnętrzne')], max_length=80, null=True)),
                ('opis', models.CharField(max_length=80, null=True)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Oczekiwanie', 'Oczekiwanie'), ('W doręczeniu', 'W doręczeniu'), ('Dostarczono', 'Dostarczono')], max_length=80, null=True)),
            ],
        ),
    ]
