# Generated by Django 3.1.3 on 2020-11-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0007_auto_20201128_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='opis',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
